services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: niscaya-antrian-app
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
      - APP_URL=https://app-cube.tech
    volumes:
      - ./storage:/app/storage