version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: niscaya-antrian-app
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./storage:/app/storage

  nginx:
    image: nginx:alpine
    container_name: niscaya-antrian-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
